package co.dito.abako.apijitpack.domain

/*
const val ERROR_PROCESSOR_API = "ERROR_PROCESSOR_API"*/


const val RETROFIT_URL_OLD_API = "RETROFIT_URL_OLD_API"
const val RETROFIT_URL_FIREBASE_API = "RETROFIT_URL_FIREBASE_API"
const val RETROFIT_URL_MOBILE_API = "RETROFIT_URL_MOBILE_API"
const val RETROFIT_URL_SHOPPING_CART_API = "RETROFIT_URL_SHOPPING_CART_API"
const val RETROFIT_URL_ADMINISTRATION_API = "RETROFIT_URL_ADMINISTRATION_API"
const val RETROFIT_URL_BUSINESS_API = "RETROFIT_URL_BUSINESS_API"
const val RETROFIT_URL_FCM_API = "RETROFIT_URL_FCM_API"

const val RETROFIT_OK_HTTP_CLIENT = "RETROFIT_OK_HTTP_CLIENT"
const val RETROFIT_OK_HTTP_CLIENT_FCM = "RETROFIT_OK_HTTP_CLIENT_FCM"
const val RETROFIT_OK_HTTP_CLIENT_FIREBASE = "RETROFIT_OK_HTTP_CLIENT_FIREBASE"

const val ERROR_PROCESSOR_API = "ERROR_PROCESSOR_API"
const val NO_INTERNET_CONNECTION = "NO_INTERNET_CONNECTION"

const val ERROR_MESSAGE_ID = -1

const val ERROR_MESSAGE = -2