package co.dito.abako.apijitpack.domain

const val NO_INTERNET_CONNECTION = "NO_INTERNET_CONNECTION"
const val ERROR_PROCESSOR_API = "ERROR_PROCESSOR_API"

const val MOBILE_RETROFIT_API_JITPACK = "MOBILE_RETROFIT_API_JITPACK"
const val MOBILE_OK_HTTP_CLIENT_API_JITPACK = "MOBILE_OK_HTTP_CLIENT_API_JITPACK"